/*   -*- buffer-read-only: t -*- vi: set ro:
 *
 *  DO NOT EDIT THIS FILE   (client-fsm.c)
 *
 *  It has been AutoGen-ed
 *  From the definitions    client.def
 *  and the template file   fsm
 *
 *  Automated Finite State Machine
 *
 *  Copyright (C) 1992-2016 Bruce Korb - all rights reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name ``Bruce Korb'' nor the name of any other
 *    contributor may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * AutoFSM IS PROVIDED BY Bruce Korb ``AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL Bruce Korb OR ANY OTHER CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define DEFINE_FSM
#include "client-fsm.h"
#include <stdio.h>

/*
 *  Do not make changes to this file, except between the START/END
 *  comments, or it will be removed the next time it is generated.
 */
/* START === USER HEADERS === DO NOT CHANGE THIS COMMENT */
/* END   === USER HEADERS === DO NOT CHANGE THIS COMMENT */

#ifndef NULL
#  define NULL 0
#endif

/**
 *  Callback routine prototype.  They return the next state.  Normally, that
 *  should be the value of the "maybe_next" argument.
 */
typedef te_client_fsm_state (client_fsm_callback_t)(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt );

static client_fsm_callback_t
    client_fsm_do_init_event_ready_to_connect,
    client_fsm_do_invalid,
    client_fsm_do_state_connect_event_got_greeting,
    client_fsm_do_state_data_event_ready_to_transfer,
    client_fsm_do_state_ehlo_event_ehlo_not_supported,
    client_fsm_do_state_ehlo_event_ehlo_response,
    client_fsm_do_state_error_event_error_processed,
    client_fsm_do_state_helo_event_helo_response,
    client_fsm_do_state_mail_event_accept,
    client_fsm_do_state_post_rcpt_event_got_another_rcpt,
    client_fsm_do_state_post_rcpt_event_send_data,
    client_fsm_do_state_quit_event_disconnected,
    client_fsm_do_state_rcpt_event_accept,
    client_fsm_do_state_send_message_body_event_accept;

/**
 *  Declare all the state transition handling routines.
 */
typedef struct transition t_client_fsm_transition;
struct transition {
    te_client_fsm_state      next_state;
    client_fsm_callback_t *  trans_proc;
};

/**
 *  State transition maps.  Map the enumeration and the event enumeration
 *  to the new state and the transition enumeration code (in that order).
 *  It is indexed by first the current state and then the event code.
 */
static const t_client_fsm_transition
client_fsm_trans_table[ CLIENT_FSM_STATE_CT ][ CLIENT_FSM_EVENT_CT ] = {

  /* STATE 0:  CLIENT_FSM_ST_INIT */
  { { CLIENT_FSM_ST_STATE_CONNECT, client_fsm_do_init_event_ready_to_connect }, /* EVT:  EVENT_READY_TO_CONNECT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_GREETING */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ACCEPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_DISCONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_ERROR_PROCESSED */
  },

  /* STATE 1:  CLIENT_FSM_ST_STATE_CONNECT */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_CONNECT */
    { CLIENT_FSM_ST_STATE_EHLO, client_fsm_do_state_connect_event_got_greeting }, /* EVT:  EVENT_GOT_GREETING */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ACCEPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_DISCONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_ERROR_PROCESSED */
  },

  /* STATE 2:  CLIENT_FSM_ST_STATE_EHLO */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_CONNECT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_GREETING */
    { CLIENT_FSM_ST_STATE_MAIL, client_fsm_do_state_ehlo_event_ehlo_response }, /* EVT:  EVENT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_STATE_HELO, client_fsm_do_state_ehlo_event_ehlo_not_supported }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ACCEPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_DISCONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_ERROR_PROCESSED */
  },

  /* STATE 3:  CLIENT_FSM_ST_STATE_HELO */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_CONNECT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_GREETING */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_STATE_MAIL, client_fsm_do_state_helo_event_helo_response }, /* EVT:  EVENT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ACCEPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_DISCONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_ERROR_PROCESSED */
  },

  /* STATE 4:  CLIENT_FSM_ST_STATE_MAIL */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_CONNECT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_GREETING */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER */
    { CLIENT_FSM_ST_STATE_RCPT, client_fsm_do_state_mail_event_accept }, /* EVT:  EVENT_ACCEPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_DISCONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_ERROR_PROCESSED */
  },

  /* STATE 5:  CLIENT_FSM_ST_STATE_RCPT */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_CONNECT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_GREETING */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER */
    { CLIENT_FSM_ST_STATE_POST_RCPT, client_fsm_do_state_rcpt_event_accept }, /* EVT:  EVENT_ACCEPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_DISCONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_ERROR_PROCESSED */
  },

  /* STATE 6:  CLIENT_FSM_ST_STATE_POST_RCPT */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_CONNECT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_GREETING */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_HELO_RESPONSE */
    { CLIENT_FSM_ST_STATE_DATA, client_fsm_do_state_post_rcpt_event_send_data }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_STATE_RCPT, client_fsm_do_state_post_rcpt_event_got_another_rcpt }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ACCEPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_DISCONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_ERROR_PROCESSED */
  },

  /* STATE 7:  CLIENT_FSM_ST_STATE_DATA */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_CONNECT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_GREETING */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_STATE_SEND_MESSAGE_BODY, client_fsm_do_state_data_event_ready_to_transfer }, /* EVT:  EVENT_READY_TO_TRANSFER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ACCEPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_DISCONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_ERROR_PROCESSED */
  },

  /* STATE 8:  CLIENT_FSM_ST_STATE_SEND_MESSAGE_BODY */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_CONNECT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_GREETING */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER */
    { CLIENT_FSM_ST_STATE_QUIT, client_fsm_do_state_send_message_body_event_accept }, /* EVT:  EVENT_ACCEPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_DISCONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_ERROR_PROCESSED */
  },

  /* STATE 9:  CLIENT_FSM_ST_STATE_QUIT */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_CONNECT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_GREETING */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ACCEPT */
    { CLIENT_FSM_ST_DONE, client_fsm_do_state_quit_event_disconnected }, /* EVT:  EVENT_DISCONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_ERROR_PROCESSED */
  },

  /* STATE 10:  CLIENT_FSM_ST_STATE_ERROR */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_CONNECT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_GREETING */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ACCEPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_DISCONNECTED */
    { CLIENT_FSM_ST_DONE, client_fsm_do_state_error_event_error_processed } /* EVT:  EVENT_ERROR_PROCESSED */
  }
};


#define Client_FsmFsmErr_off     19
#define Client_FsmEvInvalid_off  75
#define Client_FsmStInit_off     83


static char const zClient_FsmStrings[444] =
/*     0 */ "** OUT-OF-RANGE **\0"
/*    19 */ "FSM Error:  in state %d (%s), event %d (%s) is invalid\n\0"
/*    75 */ "invalid\0"
/*    83 */ "init\0"
/*    88 */ "state_connect\0"
/*   102 */ "state_ehlo\0"
/*   113 */ "state_helo\0"
/*   124 */ "state_mail\0"
/*   135 */ "state_rcpt\0"
/*   146 */ "state_post_rcpt\0"
/*   162 */ "state_data\0"
/*   173 */ "state_send_message_body\0"
/*   197 */ "state_quit\0"
/*   208 */ "state_error\0"
/*   220 */ "event_ready_to_connect\0"
/*   243 */ "event_got_greeting\0"
/*   262 */ "event_ehlo_response\0"
/*   282 */ "event_ehlo_not_supported\0"
/*   307 */ "event_helo_response\0"
/*   327 */ "event_send_data\0"
/*   343 */ "event_got_another_rcpt\0"
/*   366 */ "event_ready_to_transfer\0"
/*   390 */ "event_accept\0"
/*   403 */ "event_disconnected\0"
/*   422 */ "event_error_processed";

static const size_t aszClient_FsmStates[11] = {
    83,  88,  102, 113, 124, 135, 146, 162, 173, 197, 208 };

static const size_t aszClient_FsmEvents[12] = {
    220, 243, 262, 282, 307, 327, 343, 366, 390, 403, 422, 75 };


#define CLIENT_FSM_EVT_NAME(t)   ( (((unsigned)(t)) >= 12) \
    ? zClient_FsmStrings : zClient_FsmStrings + aszClient_FsmEvents[t])

#define CLIENT_FSM_STATE_NAME(s) ( (((unsigned)(s)) >= 11) \
    ? zClient_FsmStrings : zClient_FsmStrings + aszClient_FsmStates[s])

#ifndef EXIT_FAILURE
# define EXIT_FAILURE 1
#endif

static int client_fsm_invalid_transition( te_client_fsm_state st, te_client_fsm_event evt );

/* * * * * * * * * THE CODE STARTS HERE * * * * * * * */
/**
 *  Print out an invalid transition message and return EXIT_FAILURE
 */
static int
client_fsm_invalid_transition( te_client_fsm_state st, te_client_fsm_event evt )
{
    /* START == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */
    char const * fmt = zClient_FsmStrings + Client_FsmFsmErr_off;
    fprintf( stderr, fmt, st, CLIENT_FSM_STATE_NAME(st), evt, CLIENT_FSM_EVT_NAME(evt));
    /* END   == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */

    return EXIT_FAILURE;
}

static te_client_fsm_state
client_fsm_do_init_event_ready_to_connect(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == INIT EVENT READY TO CONNECT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == INIT EVENT READY TO CONNECT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_invalid(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == INVALID == DO NOT CHANGE THIS COMMENT  */
    exit(client_fsm_invalid_transition(initial, trans_evt));
/*  END   == INVALID == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_connect_event_got_greeting(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE CONNECT EVENT GOT GREETING == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE CONNECT EVENT GOT GREETING == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_data_event_ready_to_transfer(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE DATA EVENT READY TO TRANSFER == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE DATA EVENT READY TO TRANSFER == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_ehlo_event_ehlo_not_supported(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE EHLO EVENT EHLO NOT SUPPORTED == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE EHLO EVENT EHLO NOT SUPPORTED == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_ehlo_event_ehlo_response(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE EHLO EVENT EHLO RESPONSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE EHLO EVENT EHLO RESPONSE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_error_event_error_processed(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE ERROR EVENT ERROR PROCESSED == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE ERROR EVENT ERROR PROCESSED == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_helo_event_helo_response(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE HELO EVENT HELO RESPONSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE HELO EVENT HELO RESPONSE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_mail_event_accept(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE MAIL EVENT ACCEPT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE MAIL EVENT ACCEPT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_post_rcpt_event_got_another_rcpt(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE POST RCPT EVENT GOT ANOTHER RCPT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE POST RCPT EVENT GOT ANOTHER RCPT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_post_rcpt_event_send_data(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE POST RCPT EVENT SEND DATA == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE POST RCPT EVENT SEND DATA == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_quit_event_disconnected(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE QUIT EVENT DISCONNECTED == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE QUIT EVENT DISCONNECTED == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_rcpt_event_accept(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE RCPT EVENT ACCEPT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE RCPT EVENT ACCEPT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_send_message_body_event_accept(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE SEND MESSAGE BODY EVENT ACCEPT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE SEND MESSAGE BODY EVENT ACCEPT == DO NOT CHANGE THIS COMMENT  */
}

/**
 *  Step the FSM.  Returns the resulting state.  If the current state is
 *  CLIENT_FSM_ST_DONE or CLIENT_FSM_ST_INVALID, it resets to
 *  CLIENT_FSM_ST_INIT and returns CLIENT_FSM_ST_INIT.
 */
te_client_fsm_state
client_fsm_step(
    te_client_fsm_state client_fsm_state,
    te_client_fsm_event trans_evt,
    const char *cmd,
    void *state )
{
    te_client_fsm_state nxtSt;
    client_fsm_callback_t * pT;

    if ((unsigned)client_fsm_state >= CLIENT_FSM_ST_INVALID) {
        return CLIENT_FSM_ST_INIT;
    }

#ifndef __COVERITY__
    if (trans_evt >= CLIENT_FSM_EV_INVALID) {
        nxtSt = CLIENT_FSM_ST_INVALID;
        pT    = client_fsm_do_invalid;
    } else
#endif /* __COVERITY__ */
    {
        const t_client_fsm_transition * ttbl =
            client_fsm_trans_table[ client_fsm_state ] + trans_evt;
        nxtSt = ttbl->next_state;
        pT    = ttbl->trans_proc;
    }

    if (pT != NULL)
        nxtSt = (*pT)( cmd, state, client_fsm_state, nxtSt, trans_evt );


    /* START == FINISH STEP == DO NOT CHANGE THIS COMMENT */
    /* END   == FINISH STEP == DO NOT CHANGE THIS COMMENT */

    return nxtSt;
}
/*
 * Local Variables:
 * mode: C
 * c-file-style: "stroustrup"
 * indent-tabs-mode: nil
 * End:
 * end of client-fsm.c */
