/*   -*- buffer-read-only: t -*- vi: set ro:
 *
 *  DO NOT EDIT THIS FILE   (client-fsm.c)
 *
 *  It has been AutoGen-ed
 *  From the definitions    client.def
 *  and the template file   fsm
 *
 *  Automated Finite State Machine
 *
 *  Copyright (C) 1992-2016 Bruce Korb - all rights reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name ``Bruce Korb'' nor the name of any other
 *    contributor may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * AutoFSM IS PROVIDED BY Bruce Korb ``AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL Bruce Korb OR ANY OTHER CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define DEFINE_FSM
#include "client-fsm.h"
#include <stdio.h>

/*
 *  Do not make changes to this file, except between the START/END
 *  comments, or it will be removed the next time it is generated.
 */
/* START === USER HEADERS === DO NOT CHANGE THIS COMMENT */
/* END   === USER HEADERS === DO NOT CHANGE THIS COMMENT */

#ifndef NULL
#  define NULL 0
#endif

/**
 *  Callback routine prototype.  They return the next state.  Normally, that
 *  should be the value of the "maybe_next" argument.
 */
typedef te_client_fsm_state (client_fsm_callback_t)(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt );

static client_fsm_callback_t
    client_fsm_do_init_event_connected,
    client_fsm_do_invalid,
    client_fsm_do_state_data_sent_event_ready_to_transfer_message_body,
    client_fsm_do_state_ehlo_sent_event_ehlo_not_supported,
    client_fsm_do_state_ehlo_sent_event_got_ehlo_response,
    client_fsm_do_state_helo_sent_event_got_helo_response,
    client_fsm_do_state_mail_sent_event_server_accept,
    client_fsm_do_state_message_body_sent_event_server_accept,
    client_fsm_do_state_quit_event_send_quit,
    client_fsm_do_state_rcpt_sent_event_server_accept,
    client_fsm_do_state_ready_to_send_data_event_send_data,
    client_fsm_do_state_ready_to_send_mail_event_send_mail_from,
    client_fsm_do_state_ready_to_send_message_body_event_send_message_body,
    client_fsm_do_state_ready_to_send_rcpt_event_send_rcpt_to,
    client_fsm_do_state_use_helo_event_send_helo;

/**
 *  Declare all the state transition handling routines.
 */
typedef struct transition t_client_fsm_transition;
struct transition {
    te_client_fsm_state      next_state;
    client_fsm_callback_t *  trans_proc;
};

/**
 *  State transition maps.  Map the enumeration and the event enumeration
 *  to the new state and the transition enumeration code (in that order).
 *  It is indexed by first the current state and then the event code.
 */
static const t_client_fsm_transition
client_fsm_trans_table[ CLIENT_FSM_STATE_CT ][ CLIENT_FSM_EVENT_CT ] = {

  /* STATE 0:  CLIENT_FSM_ST_INIT */
  { { CLIENT_FSM_ST_STATE_CONNECTED, client_fsm_do_init_event_connected }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_HELO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_RCPT_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_SERVER_ACCEPT */
  },

  /* STATE 1:  CLIENT_FSM_ST_STATE_READY_TO_SEND_EHLO */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_HELO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_RCPT_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_SERVER_ACCEPT */
  },

  /* STATE 2:  CLIENT_FSM_ST_STATE_EHLO_SENT */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_STATE_READY_TO_SEND_MAIL, client_fsm_do_state_ehlo_sent_event_got_ehlo_response }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_STATE_USE_HELO, client_fsm_do_state_ehlo_sent_event_ehlo_not_supported }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_HELO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_RCPT_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_SERVER_ACCEPT */
  },

  /* STATE 3:  CLIENT_FSM_ST_STATE_USE_HELO */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_STATE_HELO_SENT, client_fsm_do_state_use_helo_event_send_helo }, /* EVT:  EVENT_SEND_HELO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_RCPT_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_SERVER_ACCEPT */
  },

  /* STATE 4:  CLIENT_FSM_ST_STATE_HELO_SENT */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_HELO */
    { CLIENT_FSM_ST_STATE_READY_TO_SEND_MAIL, client_fsm_do_state_helo_sent_event_got_helo_response }, /* EVT:  EVENT_GOT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_RCPT_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
{ CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_SERVER_ACCEPT */
  },

  /* STATE 5:  CLIENT_FSM_ST_STATE_READY_TO_SEND_MAIL */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_HELO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_HELO_RESPONSE */
    { CLIENT_FSM_ST_STATE_MAIL_SENT, client_fsm_do_state_ready_to_send_mail_event_send_mail_from }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_RCPT_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_SERVER_ACCEPT */
  },

  /* STATE 6:  CLIENT_FSM_ST_STATE_MAIL_SENT */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_HELO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_RCPT_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_STATE_READY_TO_SEND_RCPT, client_fsm_do_state_mail_sent_event_server_accept } /* EVT:  EVENT_SERVER_ACCEPT */
  },

  /* STATE 7:  CLIENT_FSM_ST_STATE_READY_TO_SEND_RCPT */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_HELO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_STATE_RCPT_SENT, client_fsm_do_state_ready_to_send_rcpt_event_send_rcpt_to }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_RCPT_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_SERVER_ACCEPT */
  },

  /* STATE 8:  CLIENT_FSM_ST_STATE_RCPT_SENT */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_HELO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_RCPT_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_STATE_RCPT_CHECK, client_fsm_do_state_rcpt_sent_event_server_accept } /* EVT:  EVENT_SERVER_ACCEPT */
  },

  /* STATE 9:  CLIENT_FSM_ST_STATE_RECPT_CHECK */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_HELO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_RCPT_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_SERVER_ACCEPT */
  },

  /* STATE 10:  CLIENT_FSM_ST_STATE_READY_TO_SEND_DATA */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_HELO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_RCPT_SENT */
    { CLIENT_FSM_ST_STATE_DATA_SENT, client_fsm_do_state_ready_to_send_data_event_send_data }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_SERVER_ACCEPT */
  },

  /* STATE 11:  CLIENT_FSM_ST_STATE_DATA_SENT */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_HELO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_RCPT_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_STATE_READY_TO_SEND_MESSAGE_BODY, client_fsm_do_state_data_sent_event_ready_to_transfer_message_body }, /* EVT:  EVENT_READY_TO_TRANSFER_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_SERVER_ACCEPT */
  },

  /* STATE 12:  CLIENT_FSM_ST_STATE_READY_TO_SEND_MESSAGE_BODY */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_HELO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_RCPT_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER_MESSAGE_BODY */
    { CLIENT_FSM_ST_STATE_MESSAGE_BODY_SENT, client_fsm_do_state_ready_to_send_message_body_event_send_message_body }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_SERVER_ACCEPT */
  },

  /* STATE 13:  CLIENT_FSM_ST_STATE_MESSAGE_BODY_SENT */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_HELO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_RCPT_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_STATE_QUIT, client_fsm_do_state_message_body_sent_event_server_accept } /* EVT:  EVENT_SERVER_ACCEPT */
  },

  /* STATE 14:  CLIENT_FSM_ST_STATE_QUIT */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_HELO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_RCPT_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_DONE, client_fsm_do_state_quit_event_send_quit }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_SERVER_ACCEPT */
  },

  /* STATE 15:  CLIENT_FSM_ST_STATE_SERVER_ERROR */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_EHLO_NOT_SUPPORTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_HELO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_HELO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_ANOTHER_RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_RCPT_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_TRANSFER_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  EVENT_SERVER_ACCEPT */
  }
};


#define Client_FsmFsmErr_off     19
#define Client_FsmEvInvalid_off  75
#define Client_FsmStInit_off     83


static char const zClient_FsmStrings[705] =
/*     0 */ "** OUT-OF-RANGE **\0"
/*    19 */ "FSM Error:  in state %d (%s), event %d (%s) is invalid\n\0"
/*    75 */ "invalid\0"
/*    83 */ "init\0"
/*    88 */ "state_ready_to_send_ehlo\0"
/*   113 */ "state_ehlo_sent\0"
/*   129 */ "state_use_helo\0"
/*   144 */ "state_helo_sent\0"
/*   160 */ "state_ready_to_send_mail\0"
/*   185 */ "state_mail_sent\0"
/*   201 */ "state_ready_to_send_rcpt\0"
/*   226 */ "state_rcpt_sent\0"
/*   242 */ "state_recpt_check\0"
/*   260 */ "state_ready_to_send_data\0"
/*   285 */ "state_data_sent\0"
/*   301 */ "state_ready_to_send_message_body\0"
/*   334 */ "state_message_body_sent\0"
/*   358 */ "state_quit\0"
/*   369 */ "state_server_error\0"
/*   388 */ "event_connected\0"
/*   404 */ "event_send_ehlo\0"
/*   420 */ "event_got_ehlo_response\0"
/*   444 */ "event_ehlo_not_supported\0"
/*   469 */ "event_send_helo\0"
/*   485 */ "event_got_helo_response\0"
/*   509 */ "event_send_mail_from\0"
/*   530 */ "event_send_rcpt_to\0"
/*   549 */ "event_got_another_rcpt\0"
/*   572 */ "event_all_rcpt_sent\0"
/*   592 */ "event_send_data\0"
/*   608 */ "event_ready_to_transfer_message_body\0"
/*   645 */ "event_send_message_body\0"
/*   669 */ "event_send_quit\0"
/*   685 */ "event_server_accept";

static const size_t aszClient_FsmStates[16] = {
    83,  88,  113, 129, 144, 160, 185, 201, 226, 242, 260, 285, 301, 334, 358,
    369 };

static const size_t aszClient_FsmEvents[16] = {
    388, 404, 420, 444, 469, 485, 509, 530, 549, 572, 592, 608, 645, 669, 685,
    75 };


#define CLIENT_FSM_EVT_NAME(t)   ( (((unsigned)(t)) >= 16) \
    ? zClient_FsmStrings : zClient_FsmStrings + aszClient_FsmEvents[t])

#define CLIENT_FSM_STATE_NAME(s) ( (((unsigned)(s)) >= 16) \
    ? zClient_FsmStrings : zClient_FsmStrings + aszClient_FsmStates[s])

#ifndef EXIT_FAILURE
# define EXIT_FAILURE 1
#endif

static int client_fsm_invalid_transition( te_client_fsm_state st, te_client_fsm_event evt );

/* * * * * * * * * THE CODE STARTS HERE * * * * * * * */
/**
 *  Print out an invalid transition message and return EXIT_FAILURE
 */
static int
client_fsm_invalid_transition( te_client_fsm_state st, te_client_fsm_event evt )
{
    /* START == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */
    char const * fmt = zClient_FsmStrings + Client_FsmFsmErr_off;
    fprintf( stderr, fmt, st, CLIENT_FSM_STATE_NAME(st), evt, CLIENT_FSM_EVT_NAME(evt));
    /* END   == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */

    return EXIT_FAILURE;
}

static te_client_fsm_state
client_fsm_do_init_event_connected(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == INIT EVENT CONNECTED == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == INIT EVENT CONNECTED == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_invalid(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == INVALID == DO NOT CHANGE THIS COMMENT  */
    exit(client_fsm_invalid_transition(initial, trans_evt));
/*  END   == INVALID == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_data_sent_event_ready_to_transfer_message_body(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE DATA SENT EVENT READY TO TRANSFER MESSAGE BODY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE DATA SENT EVENT READY TO TRANSFER MESSAGE BODY == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_ehlo_sent_event_ehlo_not_supported(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE EHLO SENT EVENT EHLO NOT SUPPORTED == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE EHLO SENT EVENT EHLO NOT SUPPORTED == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_ehlo_sent_event_got_ehlo_response(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE EHLO SENT EVENT GOT EHLO RESPONSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE EHLO SENT EVENT GOT EHLO RESPONSE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_helo_sent_event_got_helo_response(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE HELO SENT EVENT GOT HELO RESPONSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE HELO SENT EVENT GOT HELO RESPONSE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_mail_sent_event_server_accept(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE MAIL SENT EVENT SERVER ACCEPT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE MAIL SENT EVENT SERVER ACCEPT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_message_body_sent_event_server_accept(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE MESSAGE BODY SENT EVENT SERVER ACCEPT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE MESSAGE BODY SENT EVENT SERVER ACCEPT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_quit_event_send_quit(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE QUIT EVENT SEND QUIT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE QUIT EVENT SEND QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_rcpt_sent_event_server_accept(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE RCPT SENT EVENT SERVER ACCEPT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE RCPT SENT EVENT SERVER ACCEPT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_ready_to_send_data_event_send_data(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE READY TO SEND DATA EVENT SEND DATA == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE READY TO SEND DATA EVENT SEND DATA == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_ready_to_send_mail_event_send_mail_from(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE READY TO SEND MAIL EVENT SEND MAIL FROM == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE READY TO SEND MAIL EVENT SEND MAIL FROM == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_ready_to_send_message_body_event_send_message_body(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE READY TO SEND MESSAGE BODY EVENT SEND MESSAGE BODY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == READY TO SEND MESSAGE BODY EVENT SEND MESSAGE BODY == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_ready_to_send_rcpt_event_send_rcpt_to(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE READY TO SEND RCPT EVENT SEND RCPT TO == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE READY TO SEND RCPT EVENT SEND RCPT TO == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_use_helo_event_send_helo(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE USE HELO EVENT SEND HELO == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE USE HELO EVENT SEND HELO == DO NOT CHANGE THIS COMMENT  */
}

/**
 *  Step the FSM.  Returns the resulting state.  If the current state is
 *  CLIENT_FSM_ST_DONE or CLIENT_FSM_ST_INVALID, it resets to
 *  CLIENT_FSM_ST_INIT and returns CLIENT_FSM_ST_INIT.
 */
te_client_fsm_state
client_fsm_step(
    te_client_fsm_state client_fsm_state,
    te_client_fsm_event trans_evt,
    const char *cmd,
    void *state )
{
    te_client_fsm_state nxtSt;
    client_fsm_callback_t * pT;

    if ((unsigned)client_fsm_state >= CLIENT_FSM_ST_INVALID) {
        return CLIENT_FSM_ST_INIT;
    }

#ifndef __COVERITY__
    if (trans_evt >= CLIENT_FSM_EV_INVALID) {
        nxtSt = CLIENT_FSM_ST_INVALID;
        pT    = client_fsm_do_invalid;
    } else
#endif /* __COVERITY__ */
    {
        const t_client_fsm_transition * ttbl =
            client_fsm_trans_table[ client_fsm_state ] + trans_evt;
        nxtSt = ttbl->next_state;
        pT    = ttbl->trans_proc;
    }

    if (pT != NULL)
        nxtSt = (*pT)( cmd, state, client_fsm_state, nxtSt, trans_evt );


    /* START == FINISH STEP == DO NOT CHANGE THIS COMMENT */
    /* END   == FINISH STEP == DO NOT CHANGE THIS COMMENT */

    return nxtSt;
}
/*
 * Local Variables:
 * mode: C
 * c-file-style: "stroustrup"
 * indent-tabs-mode: nil
 * End:
 * end of client-fsm.c */
