/*   -*- buffer-read-only: t -*- vi: set ro:
 *
 *  DO NOT EDIT THIS FILE   (client-fsm.c)
 *
 *  It has been AutoGen-ed
 *  From the definitions    client.def
 *  and the template file   fsm
 *
 *  Automated Finite State Machine
 *
 *  Copyright (C) 1992-2016 Bruce Korb - all rights reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name ``Bruce Korb'' nor the name of any other
 *    contributor may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * AutoFSM IS PROVIDED BY Bruce Korb ``AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL Bruce Korb OR ANY OTHER CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define DEFINE_FSM
#include "client-fsm.h"
#include <stdio.h>

/*
 *  Do not make changes to this file, except between the START/END
 *  comments, or it will be removed the next time it is generated.
 */
/* START === USER HEADERS === DO NOT CHANGE THIS COMMENT */
/* END   === USER HEADERS === DO NOT CHANGE THIS COMMENT */

#ifndef NULL
#  define NULL 0
#endif

/**
 *  Callback routine prototype.  They return the next state.  Normally, that
 *  should be the value of the "maybe_next" argument.
 */
typedef te_client_fsm_state (client_fsm_callback_t)(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt );

static client_fsm_callback_t
    client_fsm_do_INIT_event_error,
    client_fsm_do_STATE_CONNECTED_event_error,
    client_fsm_do_STATE_CREATE_SOCKET_event_error,
    client_fsm_do_STATE_ERROR_event_error,
    client_fsm_do_STATE_FINISH_SENDING_MAIL_event_error,
    client_fsm_do_STATE_FREE_SOCKET_event_error,
    client_fsm_do_STATE_READY_TO_SEND_NEXT_MESSAGE_event_error,
    client_fsm_do_STATE_RECEIVE_DATA_RESPONSE_event_error,
    client_fsm_do_STATE_RECEIVE_EHLO_RESPONSE_event_error,
    client_fsm_do_STATE_RECEIVE_MAIL_FROM_RESPONSE_event_error,
    client_fsm_do_STATE_RECEIVE_MESSAGE_BODY_RESPONSE_event_error,
    client_fsm_do_STATE_RECEIVE_QUIT_RESPONSE_event_error,
    client_fsm_do_STATE_RECEIVE_RCPT_TO_RESPONSE_event_error,
    client_fsm_do_STATE_RECEIVE_SMTP_GREETING_event_error,
    client_fsm_do_STATE_SEND_DATA_event_error,
    client_fsm_do_STATE_SEND_EHLO_event_error,
    client_fsm_do_STATE_SEND_MAIL_FROM_event_error,
    client_fsm_do_STATE_SEND_MESSAGE_BODY_event_error,
    client_fsm_do_STATE_SEND_QUIT_event_error,
    client_fsm_do_STATE_SEND_RCPT_TO_event_error,
    client_fsm_do_invalid,
    client_fsm_do_state_create_socket_event_connected,
    client_fsm_do_state_finish_sending_mail_event_send_quit,
    client_fsm_do_state_ready_to_send_next_message_event_send_next_message,
    client_fsm_do_state_receive_data_response_event_send_message_body,
    client_fsm_do_state_receive_ehlo_response_event_send_mail_from,
    client_fsm_do_state_receive_message_body_response_event_ready_to_send_next_message,
    client_fsm_do_state_receive_rcpt_to_response_event_send_data,
    client_fsm_do_state_receive_smtp_greeting_event_send_ehlo,
    client_fsm_do_state_send_data_event_got_data_response,
    client_fsm_do_state_send_mail_from_event_got_mail_from_response,
    client_fsm_do_state_send_message_body_event_all_mail_sent,
    client_fsm_do_state_send_message_body_event_got_message_body_response,
    client_fsm_do_state_send_quit_event_got_quit_response,
    client_fsm_do_state_send_rcpt_to_event_got_rcpt_to_response;

/**
 *  Declare all the state transition handling routines.
 */
typedef struct transition t_client_fsm_transition;
struct transition {
    te_client_fsm_state      next_state;
    client_fsm_callback_t *  trans_proc;
};

/**
 *  State transition maps.  Map the enumeration and the event enumeration
 *  to the new state and the transition enumeration code (in that order).
 *  It is indexed by first the current state and then the event code.
 */
static const t_client_fsm_transition
client_fsm_trans_table[ CLIENT_FSM_STATE_CT ][ CLIENT_FSM_EVENT_CT ] = {

  /* STATE 0:  CLIENT_FSM_ST_INIT */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_INIT_event_error } /* EVT:  EVENT_ERROR */
  },

  /* STATE 1:  CLIENT_FSM_ST_STATE_CREATE_SOCKET */
  { { CLIENT_FSM_ST_STATE_CONNECTED, client_fsm_do_state_create_socket_event_connected }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_STATE_CREATE_SOCKET_event_error } /* EVT:  EVENT_ERROR */
  },

  /* STATE 2:  CLIENT_FSM_ST_STATE_CONNECTED */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_STATE_CONNECTED_event_error } /* EVT:  EVENT_ERROR */
  },

  /* STATE 3:  CLIENT_FSM_ST_STATE_RECEIVE_SMTP_GREETING */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_STATE_SEND_EHLO, client_fsm_do_state_receive_smtp_greeting_event_send_ehlo }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_STATE_RECEIVE_SMTP_GREETING_event_error } /* EVT:  EVENT_ERROR */
  },

  /* STATE 4:  CLIENT_FSM_ST_STATE_SEND_EHLO */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_STATE_SEND_EHLO_event_error } /* EVT:  EVENT_ERROR */
  },

  /* STATE 5:  CLIENT_FSM_ST_STATE_RECEIVE_EHLO_RESPONSE */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_STATE_SEND_MAIL_FROM, client_fsm_do_state_receive_ehlo_response_event_send_mail_from }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_STATE_RECEIVE_EHLO_RESPONSE_event_error } /* EVT:  EVENT_ERROR */
  },

  /* STATE 6:  CLIENT_FSM_ST_STATE_SEND_MAIL_FROM */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_STATE_RECEIVE_MAIL_FROM_RESPONSE, client_fsm_do_state_send_mail_from_event_got_mail_from_response }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_STATE_SEND_MAIL_FROM_event_error } /* EVT:  EVENT_ERROR */
  },

  /* STATE 7:  CLIENT_FSM_ST_STATE_RECEIVE_MAIL_FROM_RESPONSE */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_STATE_RECEIVE_MAIL_FROM_RESPONSE_event_error } /* EVT:  EVENT_ERROR */
  },

  /* STATE 8:  CLIENT_FSM_ST_STATE_SEND_RCPT_TO */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_STATE_RECEIVE_RCPT_TO_RESPONSE, client_fsm_do_state_send_rcpt_to_event_got_rcpt_to_response }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_STATE_SEND_RCPT_TO_event_error } /* EVT:  EVENT_ERROR */
  },

  /* STATE 9:  CLIENT_FSM_ST_STATE_RECEIVE_RCPT_TO_RESPONSE */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_STATE_SEND_DATA, client_fsm_do_state_receive_rcpt_to_response_event_send_data }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_STATE_RECEIVE_RCPT_TO_RESPONSE_event_error } /* EVT:  EVENT_ERROR */
  },

  /* STATE 10:  CLIENT_FSM_ST_STATE_SEND_DATA */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_STATE_RECEIVE_DATA_RESPONSE, client_fsm_do_state_send_data_event_got_data_response }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_STATE_SEND_DATA_event_error } /* EVT:  EVENT_ERROR */
  },

  /* STATE 11:  CLIENT_FSM_ST_STATE_RECEIVE_DATA_RESPONSE */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_STATE_SEND_MESSAGE_BODY, client_fsm_do_state_receive_data_response_event_send_message_body }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_STATE_RECEIVE_DATA_RESPONSE_event_error } /* EVT:  EVENT_ERROR */
  },

  /* STATE 12:  CLIENT_FSM_ST_STATE_SEND_MESSAGE_BODY */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_STATE_RECEIVE_MESSAGE_BODY_RESPONSE, client_fsm_do_state_send_message_body_event_got_message_body_response }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_STATE_FINISH_SENDING_MAIL, client_fsm_do_state_send_message_body_event_all_mail_sent }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_STATE_SEND_MESSAGE_BODY_event_error } /* EVT:  EVENT_ERROR */
  },

  /* STATE 13:  CLIENT_FSM_ST_STATE_RECEIVE_MESSAGE_BODY_RESPONSE */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_STATE_READY_TO_SEND_NEXT_MESSAGE, client_fsm_do_state_receive_message_body_response_event_ready_to_send_next_message }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_STATE_RECEIVE_MESSAGE_BODY_RESPONSE_event_error } /* EVT:  EVENT_ERROR */
  },

  /* STATE 14:  CLIENT_FSM_ST_STATE_READY_TO_SEND_NEXT_MESSAGE */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_STATE_RECEIVE_EHLO_RESPONSE, client_fsm_do_state_ready_to_send_next_message_event_send_next_message }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_STATE_READY_TO_SEND_NEXT_MESSAGE_event_error } /* EVT:  EVENT_ERROR */
  },

  /* STATE 15:  CLIENT_FSM_ST_STATE_FINISH_SENDING_MAIL */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_STATE_SEND_QUIT, client_fsm_do_state_finish_sending_mail_event_send_quit }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_STATE_FINISH_SENDING_MAIL_event_error } /* EVT:  EVENT_ERROR */
  },

  /* STATE 16:  CLIENT_FSM_ST_STATE_SEND_QUIT */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_STATE_FREE_SOCKET, client_fsm_do_state_send_quit_event_got_quit_response }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_STATE_SEND_QUIT_event_error } /* EVT:  EVENT_ERROR */
  },

  /* STATE 17:  CLIENT_FSM_ST_STATE_RECEIVE_QUIT_RESPONSE */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_STATE_RECEIVE_QUIT_RESPONSE_event_error } /* EVT:  EVENT_ERROR */
  },

  /* STATE 18:  CLIENT_FSM_ST_STATE_FREE_SOCKET */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_STATE_FREE_SOCKET_event_error } /* EVT:  EVENT_ERROR */
  },

  /* STATE 19:  CLIENT_FSM_ST_STATE_ERROR */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_CONNECTED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_EHLO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MAIL_FROM */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MAIL_FROM_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_RCPT_TO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_RCPT_TO_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_DATA_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_MESSAGE_BODY */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_MESSAGE_BODY_RESPONSE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_READY_TO_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_ALL_MAIL_SENT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_NEXT_MESSAGE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_SEND_QUIT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EVENT_GOT_QUIT_RESPONSE */
    { CLIENT_FSM_ST_STATE_ERROR, client_fsm_do_STATE_ERROR_event_error } /* EVT:  EVENT_ERROR */
  }
};


#define Client_FsmFsmErr_off     19
#define Client_FsmEvInvalid_off  75
#define Client_FsmStInit_off     83


static char const zClient_FsmStrings[914] =
/*     0 */ "** OUT-OF-RANGE **\0"
/*    19 */ "FSM Error:  in state %d (%s), event %d (%s) is invalid\n\0"
/*    75 */ "invalid\0"
/*    83 */ "init\0"
/*    88 */ "state_create_socket\0"
/*   108 */ "state_connected\0"
/*   124 */ "state_receive_smtp_greeting\0"
/*   152 */ "state_send_ehlo\0"
/*   168 */ "state_receive_ehlo_response\0"
/*   196 */ "state_send_mail_from\0"
/*   217 */ "state_receive_mail_from_response\0"
/*   250 */ "state_send_rcpt_to\0"
/*   269 */ "state_receive_rcpt_to_response\0"
/*   300 */ "state_send_data\0"
/*   316 */ "state_receive_data_response\0"
/*   344 */ "state_send_message_body\0"
/*   368 */ "state_receive_message_body_response\0"
/*   404 */ "state_ready_to_send_next_message\0"
/*   437 */ "state_finish_sending_mail\0"
/*   463 */ "state_send_quit\0"
/*   479 */ "state_receive_quit_response\0"
/*   507 */ "state_free_socket\0"
/*   525 */ "state_error\0"
/*   537 */ "event_connected\0"
/*   553 */ "event_send_ehlo\0"
/*   569 */ "event_got_ehlo_response\0"
/*   593 */ "event_send_mail_from\0"
/*   614 */ "event_got_mail_from_response\0"
/*   643 */ "event_send_rcpt_to\0"
/*   662 */ "event_got_rcpt_to_response\0"
/*   689 */ "event_send_data\0"
/*   705 */ "event_got_data_response\0"
/*   729 */ "event_send_message_body\0"
/*   753 */ "event_got_message_body_response\0"
/*   785 */ "event_ready_to_send_next_message\0"
/*   818 */ "event_all_mail_sent\0"
/*   838 */ "event_send_next_message\0"
/*   862 */ "event_send_quit\0"
/*   878 */ "event_got_quit_response\0"
/*   902 */ "event_error";

static const size_t aszClient_FsmStates[20] = {
    83,  88,  108, 124, 152, 168, 196, 217, 250, 269, 300, 316, 344, 368, 404,
    437, 463, 479, 507, 525 };

static const size_t aszClient_FsmEvents[18] = {
    537, 553, 569, 593, 614, 643, 662, 689, 705, 729, 753, 785, 818, 838, 862,
    878, 902, 75 };


#define CLIENT_FSM_EVT_NAME(t)   ( (((unsigned)(t)) >= 18) \
    ? zClient_FsmStrings : zClient_FsmStrings + aszClient_FsmEvents[t])

#define CLIENT_FSM_STATE_NAME(s) ( (((unsigned)(s)) >= 20) \
    ? zClient_FsmStrings : zClient_FsmStrings + aszClient_FsmStates[s])

#ifndef EXIT_FAILURE
# define EXIT_FAILURE 1
#endif

static int client_fsm_invalid_transition( te_client_fsm_state st, te_client_fsm_event evt );

/* * * * * * * * * THE CODE STARTS HERE * * * * * * * */
/**
 *  Print out an invalid transition message and return EXIT_FAILURE
 */
static int
client_fsm_invalid_transition( te_client_fsm_state st, te_client_fsm_event evt )
{
    /* START == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */
    char const * fmt = zClient_FsmStrings + Client_FsmFsmErr_off;
    fprintf( stderr, fmt, st, CLIENT_FSM_STATE_NAME(st), evt, CLIENT_FSM_EVT_NAME(evt));
    /* END   == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */

    return EXIT_FAILURE;
}

static te_client_fsm_state
client_fsm_do_INIT_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == INIT EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == INIT EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_STATE_CONNECTED_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE CONNECTED EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE CONNECTED EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_STATE_CREATE_SOCKET_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE CREATE SOCKET EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE CREATE SOCKET EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_STATE_ERROR_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE ERROR EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE ERROR EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_STATE_FINISH_SENDING_MAIL_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE FINISH SENDING MAIL EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE FINISH SENDING MAIL EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_STATE_FREE_SOCKET_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE FREE SOCKET EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE FREE SOCKET EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_STATE_READY_TO_SEND_NEXT_MESSAGE_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE READY TO SEND NEXT MESSAGE EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE READY TO SEND NEXT MESSAGE EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_STATE_RECEIVE_DATA_RESPONSE_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE RECEIVE DATA RESPONSE EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE RECEIVE DATA RESPONSE EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_STATE_RECEIVE_EHLO_RESPONSE_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE RECEIVE EHLO RESPONSE EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE RECEIVE EHLO RESPONSE EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_STATE_RECEIVE_MAIL_FROM_RESPONSE_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE RECEIVE MAIL FROM RESPONSE EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE RECEIVE MAIL FROM RESPONSE EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_STATE_RECEIVE_MESSAGE_BODY_RESPONSE_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE RECEIVE MESSAGE BODY RESPONSE EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE RECEIVE MESSAGE BODY RESPONSE EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_STATE_RECEIVE_QUIT_RESPONSE_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE RECEIVE QUIT RESPONSE EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE RECEIVE QUIT RESPONSE EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_STATE_RECEIVE_RCPT_TO_RESPONSE_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE RECEIVE RCPT TO RESPONSE EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE RECEIVE RCPT TO RESPONSE EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_STATE_RECEIVE_SMTP_GREETING_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE RECEIVE SMTP GREETING EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE RECEIVE SMTP GREETING EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_STATE_SEND_DATA_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE SEND DATA EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE SEND DATA EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_STATE_SEND_EHLO_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE SEND EHLO EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE SEND EHLO EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_STATE_SEND_MAIL_FROM_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE SEND MAIL FROM EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE SEND MAIL FROM EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_STATE_SEND_MESSAGE_BODY_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE SEND MESSAGE BODY EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE SEND MESSAGE BODY EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_STATE_SEND_QUIT_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE SEND QUIT EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE SEND QUIT EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_STATE_SEND_RCPT_TO_event_error(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE SEND RCPT TO EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE SEND RCPT TO EVENT ERROR == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_invalid(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == INVALID == DO NOT CHANGE THIS COMMENT  */
    exit(client_fsm_invalid_transition(initial, trans_evt));
/*  END   == INVALID == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_create_socket_event_connected(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE CREATE SOCKET EVENT CONNECTED == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE CREATE SOCKET EVENT CONNECTED == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_finish_sending_mail_event_send_quit(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE FINISH SENDING MAIL EVENT SEND QUIT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE FINISH SENDING MAIL EVENT SEND QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_ready_to_send_next_message_event_send_next_message(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE READY TO SEND NEXT MESSAGE EVENT SEND NEXT MESSAGE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE READY TO SEND NEXT MESSAGE EVENT SEND NEXT MESSAGE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_receive_data_response_event_send_message_body(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE RECEIVE DATA RESPONSE EVENT SEND MESSAGE BODY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE RECEIVE DATA RESPONSE EVENT SEND MESSAGE BODY == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_receive_ehlo_response_event_send_mail_from(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE RECEIVE EHLO RESPONSE EVENT SEND MAIL FROM == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE RECEIVE EHLO RESPONSE EVENT SEND MAIL FROM == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_receive_message_body_response_event_ready_to_send_next_message(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE RECEIVE MESSAGE BODY RESPONSE EVENT READY TO SEND NEXT MESSAGE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE RECEIVE MESSAGE BODY RESPONSE EVENT READY TO SEND NEXT MESSAGE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_receive_rcpt_to_response_event_send_data(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE RECEIVE RCPT TO RESPONSE EVENT SEND DATA == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE RECEIVE RCPT TO RESPONSE EVENT SEND DATA == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_receive_smtp_greeting_event_send_ehlo(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE RECEIVE SMTP GREETING EVENT SEND EHLO == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE RECEIVE SMTP GREETING EVENT SEND EHLO == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_send_data_event_got_data_response(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE SEND DATA EVENT GOT DATA RESPONSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE SEND DATA EVENT GOT DATA RESPONSE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_send_mail_from_event_got_mail_from_response(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE SEND MAIL FROM EVENT GOT MAIL FROM RESPONSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE SEND MAIL FROM EVENT GOT MAIL FROM RESPONSE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_send_message_body_event_all_mail_sent(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE SEND MESSAGE BODY EVENT ALL MAIL SENT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE SEND MESSAGE BODY EVENT ALL MAIL SENT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_send_message_body_event_got_message_body_response(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE SEND MESSAGE BODY EVENT GOT MESSAGE BODY RESPONSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE SEND MESSAGE BODY EVENT GOT MESSAGE BODY RESPONSE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_send_quit_event_got_quit_response(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE SEND QUIT EVENT GOT QUIT RESPONSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE SEND QUIT EVENT GOT QUIT RESPONSE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_state_send_rcpt_to_event_got_rcpt_to_response(
    const char *cmd,
    void *state,
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == STATE SEND RCPT TO EVENT GOT RCPT TO RESPONSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == STATE SEND RCPT TO EVENT GOT RCPT TO RESPONSE == DO NOT CHANGE THIS COMMENT  */
}

/**
 *  Step the FSM.  Returns the resulting state.  If the current state is
 *  CLIENT_FSM_ST_DONE or CLIENT_FSM_ST_INVALID, it resets to
 *  CLIENT_FSM_ST_INIT and returns CLIENT_FSM_ST_INIT.
 */
te_client_fsm_state
client_fsm_step(
    te_client_fsm_state client_fsm_state,
    te_client_fsm_event trans_evt,
    const char *cmd,
    void *state )
{
    te_client_fsm_state nxtSt;
    client_fsm_callback_t * pT;

    if ((unsigned)client_fsm_state >= CLIENT_FSM_ST_INVALID) {
        return CLIENT_FSM_ST_INIT;
    }

#ifndef __COVERITY__
    if (trans_evt >= CLIENT_FSM_EV_INVALID) {
        nxtSt = CLIENT_FSM_ST_INVALID;
        pT    = client_fsm_do_invalid;
    } else
#endif /* __COVERITY__ */
    {
        const t_client_fsm_transition * ttbl =
            client_fsm_trans_table[ client_fsm_state ] + trans_evt;
        nxtSt = ttbl->next_state;
        pT    = ttbl->trans_proc;
    }

    if (pT != NULL)
        nxtSt = (*pT)( cmd, state, client_fsm_state, nxtSt, trans_evt );


    /* START == FINISH STEP == DO NOT CHANGE THIS COMMENT */
    /* END   == FINISH STEP == DO NOT CHANGE THIS COMMENT */

    return nxtSt;
}
/*
 * Local Variables:
 * mode: C
 * c-file-style: "stroustrup"
 * indent-tabs-mode: nil
 * End:
 * end of client-fsm.c */
