/*   -*- buffer-read-only: t -*- vi: set ro:
 *
 *  DO NOT EDIT THIS FILE   (fsm-fsm.h)
 *
 *  It has been AutoGen-ed
 *  From the definitions    fsm.def
 *  and the template file   fsm
 *
 *  Automated Finite State Machine
 *
 *  Copyright (C) 1992-2016 Bruce Korb - all rights reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name ``Bruce Korb'' nor the name of any other
 *    contributor may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * AutoFSM IS PROVIDED BY Bruce Korb ``AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL Bruce Korb OR ANY OTHER CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 *  This file enumerates the states and transition events for a FSM.
 *
 *  te_fsm_state
 *      The available states.  FSS_INIT is always defined to be zero
 *      and FSS_INVALID and FSS_DONE are always made the last entries.
 *
 *  te_fsm_event
 *      The transition events.  These enumerate the event values used
 *      to select the next state from the current state.
 *      FSM_EV_INVALID is always defined at the end.
 */
#ifndef AUTOFSM_FSM_FSM_H_GUARD
#define AUTOFSM_FSM_FSM_H_GUARD 1
/**
 *  Finite State machine States
 *
 *  Count of non-terminal states.  The generated states INVALID and DONE
 *  are terminal, but INIT is not  :-).
 */
#define FSM_STATE_CT  8
typedef enum {
    FSM_ST_INIT,
    FSM_ST_SOCKET_STATE_INIT,
    FSM_ST_SOCKET_STATE_WAIT,
    FSM_ST_SOCKET_STATE_MAIL_CREATED_NO_RECEPIENTS,
    FSM_ST_SOCKET_STATE_RECEPIENTS_SET,
    FSM_ST_SOCKET_STATE_WRITING_DATA,
    FSM_ST_SOCKET_STATE_DELIVERING,
    FSM_ST_SOCKET_STATE_CLOSED,
    FSM_ST_INVALID,
    FSM_ST_DONE
} te_fsm_state;

/**
 *  Finite State machine transition Events.
 *
 *  Count of the valid transition events
 */
#define FSM_EVENT_CT 13
typedef enum {
    FSM_EV_HANDLE_HELO,            FSM_EV_HANDLE_EHLO,
    FSM_EV_HANDLE_MAIL,            FSM_EV_HANDLE_RCPT,
    FSM_EV_HANDLE_RSET,            FSM_EV_HANDLE_DATA,
    FSM_EV_HANDLE_QUIT,            FSM_EV_HANDLE_NOT_IMPLEMENTED,
    FSM_EV_CONNECTION_ESTABLISHED, FSM_EV_CONNECTION_FAILED,
    FSM_EV_MESSAGE_SAVED,          FSM_EV_TEXT,
    FSM_EV_CLRF_DOT_CLRF,          FSM_EV_INVALID
} te_fsm_event;

/**
 *  Step the FSM.  Returns the resulting state.  If the current state is
 *  FSM_ST_DONE or FSM_ST_INVALID, it resets to
 *  FSM_ST_INIT and returns FSM_ST_INIT.
 */
extern te_fsm_state
fsm_step(
    te_fsm_state fsm_state,
    te_fsm_event trans_evt,
    void *state,
    const char *cmd );

#endif /* AUTOFSM_FSM_FSM_H_GUARD */
/*
 * Local Variables:
 * mode: C
 * c-file-style: "stroustrup"
 * indent-tabs-mode: nil
 * End:
 * end of fsm-fsm.h */
