#ifndef _CLIENT_RE_H_
#define _CLIENT_RE_H_



#define CODE_CONNECT_OK 220
#define CODE_HELLO_OK 250
#define CODE_MAIL_OK 250
#define CODE_RCPT_OK 250
#define CODE_DATA_OK 354
#define CODE_DATA_RECEIVED_OK 250
#define CODE_QUIT_OK 221


#define RE_SERVER_RESPONSE_HELLO
#define RE_SERVER_RESPONSE_HELLO_LINES
#define RE_SERVER_RESPONSE_HELLO_LAST_LINE

#define RE_SERVER_RESPONSE_READY_FOR_MESSAGE_BODY
#define RE_SERVER_RESPONSE_BYE
#define RE_SERVER_RESPONSE_SERVER_SHUTDOWN
#define RE_SERVER_RESPONSE_ERROR

#endif
